name: hull

channels:
  - conda-forge
  - pytorch

dependencies:
  - python
  - pip
  # UI
  - jupyterlab
  - ipywidgets
  # Processing
  - numpy <=1.19.3
  - matplotlib
  - opencv
  - alphashape
  - pytorch